In [1]:
import numpy as np
import pandas as pd

In [2]:
# sample dataset with columns and errors
data ={
    "Age":[45, -999, 52, 60],
    "RestingBP": [120, 0, 140, 150],
    "City": ["Pune", "Nagar", "Indore", "Noida"],

}

df = pd.DataFrame(data)
print("Before Error Correaction:")
print(df)

Before Error Correaction:
   Age  RestingBP    City
0   45        120    Pune
1 -999          0   Nagar
2   52        140  Indore
3   60        150   Noida

In [3]:
# 1. Clean Test/Structural errors (Strip Extra spaces + conver to title case)
df['City'] = df['City'].str.strip().str.title()

In [4]:
df['City']

0      Pune
1     Nagar
2    Indore
3     Noida
Name: City, dtype: object

In [5]:
# fix invalid age values
df['Age'] = df['Age'].replace(-999, np.nan)
df['Age'] = df['Age'].fillna(df['Age'].median)

In [6]:
# fix invalid Numerical readings
df['RestingBP'] = df['RestingBP'].replace(0, np.nan)
df['RestingBP'] = df['RestingBP'].fillna(df['RestingBP'].median)

In [7]:
df

,Age,RestingBP,City
0,45.0,120.0,Pune
1,<bound method Series.median of 0 45.0\n1 ...,<bound method Series.median of 0 120.0\n1 ...,Nagar
2,52.0,140.0,Indore
3,60.0,150.0,Noida

In [9]:
# Model Building
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [10]:
# 1. Create sample dataset (features + target)
data = {
    'Age': [45, 52, 61, 39, 58, 29, 65, 48],
    'RestingBP': [120, 140, 130, 110, 150, 115, 160, 125],
    'Cholesterol': [210, 240, 190, 180, 280, 160, 310, 220],
    'HeartDisease': [0, 1, 1, 0, 1, 0, 1, 0]
}

In [11]:
df = pd.DataFrame(data)

In [13]:
X = df[['Age', 'RestingBP', 'Cholesterol']]
y = df['HeartDisease']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
model = DecisionTreeClassifier(random_state = 42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [17]:
y_pred = model.predict(X_test)

In [22]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [23]:
new_patient = [[150, 135, 230]]
prediction = model.predict(new_patient)
print("Prediction for New Patient:", prediction)

Prediction for New Patient: [1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [25]:
print("New patient prediction")
if prediction[0] == 1:
    print("Patient has Heart Disease")
else:
    print("Patient does not have Heart Disease")

New patient prediction
Patient has Heart Disease